"""Updating Show

Revision ID: 216b7de41791
Revises: 602a721a289b
Create Date: 2020-04-07 17:29:59.798461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216b7de41791'
down_revision = '602a721a289b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'id')
    # ### end Alembic commands ###
